# Generated by Django 4.1.4 on 2023-02-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_size_title_alter_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='title',
        ),
    ]
