# Generated by Django 4.1.4 on 2023-02-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_size_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='size',
            name='title',
        ),
        migrations.RemoveField(
            model_name='size',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='Variatns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.PositiveIntegerField()),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size')),
            ],
        ),
    ]
