# Generated by Django 4.1.4 on 2023-02-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_size_product_variant_remove_size_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variatns',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
