# Generated by Django 4.1.4 on 2023-02-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_variatns_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variatns',
            name='color_variant',
        ),
    ]
