# Generated by Django 4.1.4 on 2023-02-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_variatns_color_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
