# Generated by Django 4.1.4 on 2023-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('type_photo', models.CharField(choices=[('All', 'All'), ('پرتره', 'پرتره'), ('تبلیغاتی', 'تبلیغاتی'), ('عروس', 'عروس'), ('فضای باز', 'فضای باز'), ('تولد', 'تولد'), ('مراسم', 'مراسم'), ('کودک', 'کودک'), ('اسپرت', 'اسپرت')], default='All', max_length=10)),
            ],
        ),
    ]
