# Generated by Django 4.1.4 on 2023-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='type_photo',
            field=models.CharField(choices=[('All', 'All'), ('portrait', 'پرتره'), ('adv', 'تبلیغاتی'), ('weeding', 'عروس'), ('outdoor', 'فضای باز'), ('تولد', 'تولد'), ('مراسم', 'مراسم'), ('کودک', 'کودک'), ('اسپرت', 'اسپرت')], default='All', max_length=10),
        ),
    ]
