# Generated by Django 4.1.7 on 2023-03-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_alter_photos_type_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='information',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='price',
        ),
    ]
