# Generated by Django 4.1.7 on 2023-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_remove_photos_information_remove_photos_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='type_photo',
            field=models.CharField(choices=[('All', 'All'), ('portrait', 'پرتره'), ('adv', 'تبلیغاتی'), ('studio', 'studio'), ('outdoor', 'فضای باز'), ('تولد', 'تولد'), ('مراسم', 'مراسم'), ('کودک', 'کودک')], default='All', max_length=10),
        ),
    ]
